import React, { useCallback, useEffect, useState } from 'react';
import { createRoot } from 'react-dom/client';
import { ArrowRight, BookOpen, Check, ChevronLeft, Download, Headphones, Home, Leaf, Lightbulb, Map, MessageCircle, Mic, RotateCcw, Search, Settings as SettingsIcon, ShieldCheck, Square, Upload, Volume2, X } from 'lucide-react';
import type { Bootstrap, Lesson, ReviewItem, Settings } from '../shared/types';
import { api, post } from './api';
import { useSpeech, type Speech } from './speech';
import { ArtPath, Button, Empty, Heading, Sentence } from './ui';
import { Study } from './Study';
import { VoiceSettings } from './VoiceSettings';
import { AudioControls } from './AudioControls';
import './style.css';

type View = 'home' | 'lessons' | 'study' | 'review' | 'settings';
function readView(): { view: View; lessonId: number | null } {
  const [name, number] = location.hash.replace('#', '').split('/');
  return { view: ['home', 'lessons', 'study', 'review', 'settings'].includes(name) ? name as View : 'home', lessonId: number && Number(number) >= 1 && Number(number) <= 50 ? Number(number) : null };
}
function App() {
  const [bootstrap, setBootstrap] = useState<Bootstrap | null>(null);
  const [lessons, setLessons] = useState<Lesson[]>([]);
  const [route, setRoute] = useState(readView);
  const [message, setMessage] = useState('');
  const [loadError, setLoadError] = useState('');
  const [welcome, setWelcome] = useState(false);
  const notice = useCallback((text: string) => setMessage(text), []);
  const speech = useSpeech(notice);
  const refresh = useCallback(async () => { setBootstrap(await api<Bootstrap>('/bootstrap')); }, []);
  const load = useCallback(async () => { try { const [initial, content] = await Promise.all([api<Bootstrap>('/bootstrap'), api<Lesson[]>('/lessons')]); setBootstrap(initial); setLessons(content); setLoadError(''); } catch (error) { setLoadError((error as Error).message); } }, []);
  useEffect(() => { void load(); }, [load]);
  useEffect(() => { const update = () => { speech.stop(); setRoute(readView()); setMessage(''); }; window.addEventListener('hashchange', update); return () => window.removeEventListener('hashchange', update); }, [speech.stop]);
  useEffect(() => { document.documentElement.classList.toggle('large-text', Boolean(bootstrap?.settings.largeText)); }, [bootstrap?.settings.largeText]);
  useEffect(() => { const timer = setTimeout(() => document.querySelector<HTMLHeadingElement>('h1')?.focus({ preventScroll: true }), 30); return () => clearTimeout(timer); }, [route.view, route.lessonId]);
  async function updateSettings(changes: Partial<Settings> & { apiKey?: string }) { const settings = await api<Settings>('/settings', { method: 'PATCH', body: JSON.stringify(changes) }); setBootstrap(previous => previous ? { ...previous, settings } : previous); return settings; }
  function navigate(view: View, lessonId?: number) { speech.stop(); setMessage(''); location.hash = view + (lessonId ? '/' + lessonId : ''); window.scrollTo({ top: 0, behavior: 'instant' }); }
  async function selectLesson(id: number) { try { await updateSettings({ currentLessonId: id }); await refresh(); navigate('study', id); } catch (error) { notice((error as Error).message); } }
  if (loadError) return <main className="load-screen"><span className="brand-mark">日</span><h1>暂时没有连上学习服务</h1><p>{loadError}</p><p>{['localhost', '127.0.0.1', '[::1]'].includes(location.hostname) ? '请先双击“一键启动”，再试一次。' : '请检查网络，稍后重新连接。'}</p><Button onClick={load}>重新连接 <RotateCcw size={18}/></Button></main>;
  if (!bootstrap || !lessons.length) return <main className="load-screen" aria-busy="true"><span className="brand-mark">日</span><h1>正在打开你的学习角落……</h1></main>;
  const settings = bootstrap.settings;
  const current = lessons.find(lesson => lesson.id === (route.lessonId || settings.currentLessonId)) || lessons[0];
  const homeLesson = lessons.find(lesson => lesson.id === settings.currentLessonId) || lessons[0];
  const navItems: { id: View; label: string; icon: typeof Home }[] = [{ id: 'home', label: '今天学什么', icon: Home }, { id: 'lessons', label: '50 课地图', icon: Map }, { id: 'review', label: '复习卡点', icon: RotateCcw }, { id: 'settings', label: '学习设置', icon: SettingsIcon }];
  return <div className="app-layout"><a className="skip-link" href="#main" onClick={event => { event.preventDefault(); document.getElementById('main')?.focus(); }}>跳到学习内容</a><aside className="sidebar"><button className="brand" onClick={() => navigate('home')} aria-label="回到首页"><span className="brand-mark">日</span><span><strong>日语，慢慢来</strong><small>逐课学，开口用</small></span></button><div className="side-caption">我的学习角落</div><nav aria-label="主导航">{navItems.map(item => <button key={item.id} aria-label={item.label} className={route.view === item.id || item.id === 'lessons' && route.view === 'study' ? 'active' : ''} onClick={() => navigate(item.id)} aria-current={route.view === item.id ? 'page' : undefined}><item.icon size={21}/><span>{item.label}</span>{item.id === 'review' && bootstrap.dueReviews.length > 0 && <b className="nav-count">{bootstrap.dueReviews.length}</b>}</button>)}</nav><div className="sidebar-note"><Leaf size={23}/><strong>不用一次学会很多。</strong><p>听懂一句，回应一句。<br/>今天就多会一点。</p></div><div className="local-indicator"><span/><ShieldCheck size={15}/>{bootstrap.deployment === 'web' ? '记录保存在你的服务器' : '只在这台电脑保存'}</div></aside>
    <div className="main-area"><header className="topbar"><span className="topbar-caption">大家的日语 · 第二版</span><div className="topbar-actions"><span className={`ai-indicator ${settings.hasApiKey ? 'ready' : ''}`}>{settings.hasApiKey ? 'DeepSeek 已配置' : 'AI 待配置'}</span><button className="tool-button" aria-pressed={settings.largeText} onClick={() => void updateSettings({ largeText: !settings.largeText }).catch(error => notice(error.message))}>大字</button><button className="tool-button" onClick={() => { if (speech.sourceId === 'page-narration' && speech.status !== 'idle') speech.stop(); else { const text = route.view === 'home' ? `今天，把一句日语用起来。你当前选择第${homeLesson.id}课。可以继续学习，或者复习${bootstrap.dueReviews.length}个到期卡点。` : route.view === 'lessons' ? '这里是两册教材的五十课地图。先选上册或者下册，再点你想练的课。所有课程都可以直接进入。' : route.view === 'review' ? '先回想，再看答案。你可以听问题，试着说出来，然后按实际情况选择。' : route.view === 'settings' ? '在这里选择你的当前课，配置 DeepSeek 密钥，测试麦克风与中文日文朗读。也可以导出学习记录。' : `第${current.id}课。${current.canDo}。按看懂、听懂、自己说和用起来四步练习。每张卡可以点听讲解。`; speech.say(text, 'zh-CN', 1, 'page-narration'); } }}>{speech.sourceId === 'page-narration' && speech.status !== 'idle' ? <Square size={17}/> : <Volume2 size={18}/>}<span>{speech.sourceId === 'page-narration' && speech.status !== 'idle' ? '停止朗读' : '听讲解'}</span></button></div><AudioControls speech={speech} sourceId="page-narration"/></header>
      <main id="main" className="page-content" tabIndex={-1}>
        {message && <div className="message-banner" role="status"><span>{message}</span><button aria-label="关闭提示" onClick={() => setMessage('')}><X size={20}/></button></div>}
        {route.view === 'home' && <><Heading eyebrow="今天，也向前一小步" title={<>把一句日语，<em>用起来。</em></>} description="看懂 → 听懂 → 自己说。每天只接好一小段。"><span className="soft-badge"><Leaf size={17}/>按自己的节奏</span></Heading><section className="home-hero"><div className="hero-copy"><div className="lesson-kicker">{settings.setupComplete ? `正在学习 · 初级 ${homeLesson.volume === 1 ? 'Ⅰ' : 'Ⅱ'}` : '先选起点，再开始'}</div><h2>{settings.setupComplete ? `第 ${String(homeLesson.id).padStart(2, '0')} 课` : '从你熟悉的那一课开始。'}</h2><p className="hero-lesson-title">{settings.setupComplete ? homeLesson.title : '不必从头重来，也不用赶进度。'}</p><p className="hero-goal">{settings.setupComplete ? homeLesson.canDo : '选好当前课，之后每次打开都能接着练。'}</p><Button onClick={() => settings.setupComplete ? void selectLesson(homeLesson.id) : setWelcome(true)}>{settings.setupComplete ? '继续这一课' : '选择我的起点'}<ArrowRight size={20}/></Button></div><ArtPath/></section><div className="home-cards"><button className="home-review" onClick={() => navigate('review')}><span className="tile-icon peach"><RotateCcw size={26}/></span><div><span className="card-kicker">先想起来，再看答案</span><h2>复习卡点 <span>{bootstrap.dueReviews.length}</span></h2><p>{bootstrap.dueReviews.length ? '几张小卡，练熟那些说不出来的地方。' : '今天还没有到期卡点，可以安心继续学。'}</p></div><ArrowRight size={23}/></button><button className="home-map" onClick={() => navigate('lessons')}><span className="tile-icon lavender"><Map size={26}/></span><div><span className="card-kicker">初级 Ⅰ + 初级 Ⅱ</span><h2>去 50 课地图</h2><p>换一课，或者回头练。</p></div><ArrowRight size={23}/></button></div><section className="daily-plan"><div className="section-header"><div><p className="eyebrow">给听与说，留一点位置</p><h2>今天的练习节奏</h2></div><div className="segmented" aria-label="每日时间"><button aria-pressed={settings.dailyMinutes === 60} onClick={() => void updateSettings({ dailyMinutes: 60 }).catch(error => notice(error.message))}>60 分钟</button><button aria-pressed={settings.dailyMinutes === 15} onClick={() => void updateSettings({ dailyMinutes: 15 }).catch(error => notice(error.message))}>15 分钟短练</button></div></div><div className="time-track">{(settings.dailyMinutes === 60 ? [{ label: '教材与习题', minutes: 25, icon: BookOpen }, { label: '听一小段', minutes: 15, icon: Headphones }, { label: '合书说', minutes: 10, icon: Mic }, { label: '场景对话', minutes: 10, icon: MessageCircle }] : [{ label: '回想一句', minutes: 3, icon: RotateCcw }, { label: '听一小段', minutes: 4, icon: Headphones }, { label: '自己说', minutes: 3, icon: Mic }, { label: '场景对话', minutes: 5, icon: MessageCircle }]).map((part, i) => <div key={part.label} className={`time-block time-${i}`} style={{ flex: part.minutes }}><part.icon size={21}/><strong>{part.minutes}<small>分钟</small></strong><span>{part.label}</span></div>)}</div><p className="tiny-note">这是安排建议。难的地方可以多练一天，不会自动倒计时催你。</p></section><div className="home-bottom"><span><Check size={16}/>{bootstrap.totals.independent} 个任务留下独立完成的记录</span><button className="text-button" onClick={() => navigate('settings')}>检查 AI 与语音 <ArrowRight size={16}/></button></div></>}
        {route.view === 'lessons' && <CourseMap lessons={lessons} bootstrap={bootstrap} choose={selectLesson}/>}
        {route.view === 'study' && <><button className="text-button back-link" onClick={() => navigate('lessons')}><ChevronLeft size={17}/>回到课程地图</button><Heading eyebrow={`初级 ${current.volume === 1 ? 'Ⅰ' : 'Ⅱ'} · 第 ${String(current.id).padStart(2, '0')} 课`} title={current.title} description={current.canDo}/><Study key={current.id} lesson={current} bootstrap={bootstrap} speech={speech} notice={notice} refresh={refresh}/></>}
        {route.view === 'review' && <Reviews bootstrap={bootstrap} refresh={refresh} speech={speech} notice={notice} learn={() => void selectLesson(homeLesson.id)}/>}
        {route.view === 'settings' && <SettingsPage bootstrap={bootstrap} lessons={lessons} update={updateSettings} refresh={refresh} speech={speech} notice={notice}/>}
      </main><footer className="app-footer"><span>一次一句，慢慢来。</span><span>原创练习 · 配合《大家的日语》第二版使用</span>{bootstrap.deployment === 'web' && bootstrap.publicSite?.icpNumber && <a href="https://beian.miit.gov.cn/" target="_blank" rel="noopener noreferrer">{bootstrap.publicSite.icpNumber}</a>}</footer>
    </div>
    {welcome && <Onboarding deployment={bootstrap.deployment} current={settings.currentLessonId} lessons={lessons} close={() => setWelcome(false)} complete={async (lessonId, key) => { await updateSettings({ currentLessonId: lessonId, setupComplete: true, ...(key ? { apiKey: key } : {}) }); setWelcome(false); await selectLesson(lessonId); }} notice={notice}/>}
  </div>;
}

function CourseMap({ lessons, bootstrap, choose }: { lessons: Lesson[]; bootstrap: Bootstrap; choose: (id: number) => Promise<void> }) {
  const [volume, setVolume] = useState<1 | 2>(bootstrap.settings.currentLessonId <= 25 ? 1 : 2);
  const [search, setSearch] = useState('');
  const filtered = lessons.filter(lesson => lesson.volume === volume && (!search || `${lesson.id} ${lesson.title} ${lesson.canDo} ${lesson.grammar.map(g => g.title).join(' ')}`.includes(search.trim())));
  return <><Heading eyebrow="你的课程地图" title={<>一步一课，<em>走到能用。</em></>} description="所有课程都可以直接进入。学过的内容，也值得再开口练一次。"/><div className="map-toolbar"><div className="segmented"><button aria-pressed={volume === 1} onClick={() => setVolume(1)}>初级 Ⅰ · 1–25</button><button aria-pressed={volume === 2} onClick={() => setVolume(2)}>初级 Ⅱ · 26–50</button></div><label className="search-box"><Search size={20}/><input aria-label="查找课程" placeholder="课次 / 语法 / 场景" value={search} onChange={event => setSearch(event.target.value)}/></label></div><div className="course-grid">{filtered.map(lesson => { const record = bootstrap.progress.find(p => p.lessonId === lesson.id); const active = lesson.id === bootstrap.settings.currentLessonId; return <button className={`course-card ${active ? 'current' : ''}`} key={lesson.id} onClick={() => void choose(lesson.id)}><span className="course-top"><span className="course-number">{String(lesson.id).padStart(2, '0')}</span><span className="course-state">{active ? '当前选择' : record ? '练习过' : '随时开始'}</span></span><h2>{lesson.title}</h2><p>{lesson.canDo}</p><span className="course-bottom"><span>{lesson.grammar.length} 个语法 · 2 个场景</span><ArrowRight size={18}/></span></button>; })}</div>{!filtered.length && <Empty title="换个关键词试试" text="可以输入课次数字，或者本课语法。"/>}</>;
}

function Reviews({ bootstrap, refresh, speech, notice, learn }: { bootstrap: Bootstrap; refresh: () => Promise<void>; speech: Speech; notice: (text: string) => void; learn: () => void }) {
  const [show, setShow] = useState(false);
  const [pending, setPending] = useState(false);
  const [usedHint, setUsedHint] = useState(false);
  const item = bootstrap.dueReviews[0];
  async function rate(rating: 'again' | 'hint' | 'good') { if (!item || pending) return; setPending(true); speech.stop(); try { await post(`/reviews/${item.id}/rate`, { rating: rating === 'good' && usedHint ? 'hint' : rating }); await refresh(); setShow(false); setUsedHint(false); notice('这一张已记录，下次会按你的完成情况安排。'); } catch (error) { notice((error as Error).message); } finally { setPending(false); } }
  return <><Heading eyebrow="先提取，再核对" title={<>把卡住的，<em>练熟一点。</em></>} description={`今天到期 ${bootstrap.dueReviews.length} 张。先回想，不急着看答案。`}/>{item ? <section className="study-card review-card"><div className="card-label"><RotateCcw size={18}/>来自第 {item.lessonId} 课</div><h2>{item.goal}</h2><Button secondary onClick={() => speech.say(item.goal, 'zh-CN', 1, `review:${item.id}`)}><Volume2 size={19}/>听问题</Button><AudioControls speech={speech} sourceId={`review:${item.id}`}/><div className="review-answer">{show ? <Sentence example={item.answer} speech={speech} furigana={bootstrap.settings.furigana}/> : <div className="no-hint"><Mic size={44}/><p>合上提示，先试着说。</p></div>}</div><div className="row-actions">{!show && <Button secondary onClick={() => { setShow(true); setUsedHint(true); }}>给我答案提示 <Lightbulb size={18}/></Button>}<Button secondary disabled={pending} onClick={() => void rate('again')}>还不会</Button><Button secondary disabled={pending} onClick={() => void rate('hint')}>用提示完成</Button><Button disabled={pending} onClick={() => void rate('good')}><Check size={18}/>独立说出来了</Button></div><p className="tiny-note">用过答案提示，会记录为“用提示完成”，下次再试着独立说。</p></section> : <Empty title="今天的卡点，已经练完。" text={bootstrap.totals.reviews ? '其他卡片会在到期时出现。现在可以继续一小课。' : '学习时点“加入复习”，明天就在这里再练。'}><Button onClick={learn}>继续学习 <ArrowRight size={18}/></Button></Empty>}</>;
}

function SettingsPage({ bootstrap, lessons, update, refresh, speech, notice }: { bootstrap: Bootstrap; lessons: Lesson[]; update: (changes: Partial<Settings> & { apiKey?: string }) => Promise<Settings>; refresh: () => Promise<void>; speech: Speech; notice: (text: string) => void }) {
  const [key, setKey] = useState(''); const [model, setModel] = useState(bootstrap.settings.model); const [pending, setPending] = useState(false); const [restoreFile, setRestoreFile] = useState<{ name: string; backup: unknown } | null>(null);
  const settings = bootstrap.settings;
  async function save() { setPending(true); try { await update({ model, ...(key.trim() ? { apiKey: key.trim() } : {}) }); setKey(''); notice(bootstrap.deployment === 'web' ? '设置已保存在你的服务器。' : '设置已保存在本机。'); } catch (error) { notice((error as Error).message); } finally { setPending(false); } }
  async function testMic() { try { const stream = await navigator.mediaDevices.getUserMedia({ audio: true }); stream.getTracks().forEach(track => track.stop()); notice('麦克风权限正常。去“用起来”录一句日语，确认识别效果。'); } catch { notice('未能打开麦克风。请检查浏览器和系统的麦克风权限；网站需要使用 HTTPS 地址。'); } }
  async function downloadBackup() { try { const backup = await api('/backup'); const url = URL.createObjectURL(new Blob([JSON.stringify(backup, null, 2)], { type: 'application/json' })); const a = document.createElement('a'); a.href = url; a.download = `日语学习记录-${new Date().toISOString().slice(0, 10)}.json`; a.click(); URL.revokeObjectURL(url); } catch (error) { notice((error as Error).message); } }
  return <><Heading eyebrow="你的学习偏好" title={<>调到<em>适合你的样子。</em></>} description={bootstrap.deployment === 'web' ? '设置与密钥保存在你的服务器。密钥不会出现在学习备份中。' : '设置只保存在这台电脑。密钥不会出现在学习备份中。'}/><div className="settings-grid"><section className="settings-card"><span className="tile-icon lavender"><BookOpen/></span><h2>从哪一课开始</h2><label>当前选择<select value={settings.currentLessonId} onChange={event => void update({ currentLessonId: Number(event.target.value), setupComplete: true }).catch(error => notice(error.message))}>{lessons.map(lesson => <option value={lesson.id} key={lesson.id}>第 {lesson.id} 课 · {lesson.title}</option>)}</select></label><p className="tiny-note">选择当前课，不会把前面的课标为已掌握。</p>{([{ field: 'largeText', title: '大字模式', description: '更大的文字与间距' }, { field: 'furigana', title: '显示日语读音', description: '句子上方显示假名读音' }, { field: 'autoplay', title: '自动朗读 AI 回答', description: '发送后自动听到日语' }] as const).map(item => <label className="toggle-row" key={item.field}><span><strong>{item.title}</strong><small>{item.description}</small></span><input type="checkbox" checked={settings[item.field]} onChange={event => void update({ [item.field]: event.target.checked }).catch(error => notice(error.message))}/></label>)}</section>
      <section className="settings-card"><span className="tile-icon lime"><MessageCircle/></span><h2>连接 DeepSeek</h2><p className="status-line"><span className={settings.hasApiKey ? 'status-dot ready' : 'status-dot'}/>{settings.hasApiKey ? '已配置密钥，实际可用性以调用结果为准' : '尚未配置，可以先学课程'}</p><label>API 密钥<input type="password" autoComplete="off" value={key} onChange={event => setKey(event.target.value)} placeholder={settings.hasApiKey ? '填写新密钥可替换，留空保持不变' : '在这里填写你的 DeepSeek API 密钥'}/></label><label>模型<input value={model} onChange={event => setModel(event.target.value)} maxLength={100}/></label><Button onClick={save} disabled={pending}>{pending ? '保存中……' : '保存 AI 设置'}<Check size={18}/></Button><p className="tiny-note">对话会联网调用 DeepSeek，费用按你的 API 账户计算。</p></section>
      <VoiceSettings speech={speech} notice={notice} deployment={bootstrap.deployment}/>
      <section className="settings-card"><span className="tile-icon peach"><Mic/></span><h2>麦克风与朗读</h2><p className="status-line"><span className={`status-dot ${bootstrap.speech.ready ? 'ready' : ''}`}/>{bootstrap.speech.message}</p><div className="row-actions"><Button secondary onClick={testMic}><Mic size={18}/>测试麦克风</Button><Button secondary onClick={() => speech.say('こんにちは。ゆっくり練習しましょう。', 'ja-JP', 1, 'settings-voice-test')}><Volume2 size={18}/>试听日语</Button><Button secondary onClick={() => speech.say('我们一次只练一句，慢慢来。', 'zh-CN', 1, 'settings-voice-test')}>试听中文</Button></div><AudioControls speech={speech} sourceId="settings-voice-test"/><p className="tiny-note">{bootstrap.deployment === 'web' ? '录音会上传到你的服务器识别，完成后删除。中文讲解使用当前设备的系统声音；缺少声音时，请在设备设置中添加语音包。' : '首次请双击项目里的“安装本机语音”。缺少朗读声音时，在 Windows → 时间和语言 → 语音中添加中文、日文语音包。'}</p><button className="text-button" onClick={() => void refresh().then(() => notice('语音安装状态已更新。')).catch(error => notice(error.message))}>重新检查语音状态 <RotateCcw size={16}/></button></section>
      <section className="settings-card"><span className="tile-icon blue"><ShieldCheck/></span><h2>保管学习记录</h2><p className="tiny-note">导出包含文字、评分与录音信息，不含音频文件。音频保留 90 天，完整备份需保存数据目录。</p><p>{bootstrap.deployment === 'web' ? '进度、对话与复习存在你的服务器。导出一份，下载到当前设备备份。未发送的草稿只保留在当前浏览器。' : '进度、对话与复习存在本机。导出一份，留作备份。'}</p><div className="row-actions"><Button secondary onClick={downloadBackup}><Download size={18}/>导出记录</Button><label className="button secondary upload-button"><Upload size={18}/>选择备份<input aria-label="选择学习备份文件" type="file" accept="application/json,.json" onChange={async event => { const file = event.target.files?.[0]; if (!file) return; try { if (file.size > 16 * 1024 * 1024) throw new Error('备份文件不能超过 16 MB。'); setRestoreFile({ name: file.name, backup: JSON.parse(await file.text()) }); } catch (error) { notice((error as Error).message); } event.target.value = ''; }}/></label></div>{restoreFile && <div className="restore-confirm"><p>恢复“{restoreFile.name}”会替换当前学习记录，保留 API 密钥。</p><div className="row-actions"><Button disabled={pending} onClick={async () => { setPending(true); try { await post('/restore', { backup: restoreFile.backup }); await refresh(); setRestoreFile(null); notice('学习记录已恢复。'); } catch (error) { notice((error as Error).message); } finally { setPending(false); } }}>确认恢复</Button><Button secondary onClick={() => setRestoreFile(null)}>取消</Button></div></div>}</section>
    </div><details className="source-details"><summary>教材、模型与使用说明</summary><p>课程按《大家的日语》第二版初级Ⅰ（1–25课）和初级Ⅱ（26–50课）的主要语法目标整理。词汇、例句、听力与练习为原创辅助材料，不是原版课本或官方题库。</p><p><a href="https://plus.3anet.co.jp/mnc/contents/" target="_blank" rel="noreferrer">出版社教材说明</a> · <a href="https://api-docs.deepseek.com/" target="_blank" rel="noreferrer">DeepSeek 接口</a> · <a href="https://github.com/ggml-org/whisper.cpp" target="_blank" rel="noreferrer">语音识别组件</a></p><p>未验证的 AI 回复不代表标准答案。遇到疑问，可与教材核对。本机朗读为合成声音。</p></details></>;
}

function Onboarding({ current, lessons, close, complete, notice, deployment = 'local' }: { current: number; lessons: Lesson[]; close: () => void; complete: (id: number, key: string) => Promise<void>; notice: (text: string) => void; deployment?: 'local' | 'web' }) {
  const [id, setId] = useState(current); const [key, setKey] = useState(''); const [pending, setPending] = useState(false); const [micStatus, setMicStatus] = useState('');
  useEffect(() => { const dialog = document.getElementById('welcome-dialog') as HTMLDialogElement; dialog.showModal(); const onCancel = () => close(); dialog.addEventListener('cancel', onCancel); return () => dialog.removeEventListener('cancel', onCancel); }, []);
  return <dialog id="welcome-dialog" className="welcome-dialog" aria-labelledby="welcome-title"><div className="dialog-top"><span className="tile-icon lime"><Leaf/></span><button className="icon-button" aria-label="关闭起点设置" onClick={close}><X/></button></div><p className="eyebrow">欢迎来到你的学习角落</p><h2 id="welcome-title">从你正在学的地方开始。</h2><p>前面的课可以随时回头练。</p><label>选一课<select value={id} onChange={event => setId(Number(event.target.value))}>{lessons.map(lesson => <option value={lesson.id} key={lesson.id}>第 {lesson.id} 课 · {lesson.title}</option>)}</select></label><label>DeepSeek API 密钥（可以稍后设置）<input type="password" autoComplete="off" value={key} onChange={event => setKey(event.target.value)} placeholder={deployment === 'web' ? '只保存在你的服务器后端' : '只保存在本机后端'}/></label><Button secondary onClick={async () => { try { const stream = await navigator.mediaDevices.getUserMedia({ audio: true }); stream.getTracks().forEach(track => track.stop()); setMicStatus('麦克风可以打开。开始后可录一句日语。'); } catch { setMicStatus('麦克风未开启，可以先打字。稍后在设置里重试。'); } }}><Mic size={18}/>测试麦克风</Button>{micStatus && <p role="status" className="tiny-note">{micStatus}</p>}<Button disabled={pending} onClick={async () => { setPending(true); try { await complete(id, key.trim()); } catch (error) { notice((error as Error).message); } finally { setPending(false); } }}>{pending ? '正在保存' : '从这一课开始'}<ArrowRight size={18}/></Button></dialog>;
}

createRoot(document.getElementById('root')!).render(<React.StrictMode><App/></React.StrictMode>);
